// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI0VZzeriTGGgzdliHDcjr6fpMXltZ8Sg',
    appId: '1:409987999840:web:ba246b192177c55054fb05',
    messagingSenderId: '409987999840',
    projectId: 'travel-expense-tracker-23ba9',
    authDomain: 'travel-expense-tracker-23ba9.firebaseapp.com',
    storageBucket: 'travel-expense-tracker-23ba9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyDKWVHsK0Mz-cRATGwwEZaTaL-6AhPAQ',
    appId: '1:409987999840:android:a51cd57c50af526c54fb05',
    messagingSenderId: '409987999840',
    projectId: 'travel-expense-tracker-23ba9',
    storageBucket: 'travel-expense-tracker-23ba9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4BQJxz7ixMy5zAzdrmJ6C5_CXuZgNiNs',
    appId: '1:409987999840:ios:dc1d9ce8c8ca668954fb05',
    messagingSenderId: '409987999840',
    projectId: 'travel-expense-tracker-23ba9',
    storageBucket: 'travel-expense-tracker-23ba9.firebasestorage.app',
    iosBundleId: 'com.example.travelExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4BQJxz7ixMy5zAzdrmJ6C5_CXuZgNiNs',
    appId: '1:409987999840:ios:dc1d9ce8c8ca668954fb05',
    messagingSenderId: '409987999840',
    projectId: 'travel-expense-tracker-23ba9',
    storageBucket: 'travel-expense-tracker-23ba9.firebasestorage.app',
    iosBundleId: 'com.example.travelExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI0VZzeriTGGgzdliHDcjr6fpMXltZ8Sg',
    appId: '1:409987999840:web:775259fa69a2b97954fb05',
    messagingSenderId: '409987999840',
    projectId: 'travel-expense-tracker-23ba9',
    authDomain: 'travel-expense-tracker-23ba9.firebaseapp.com',
    storageBucket: 'travel-expense-tracker-23ba9.firebasestorage.app',
  );
}
